# Generated by Django 4.1.13 on 2026-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="CmsContentMeta",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=64, unique=True)),
                        ("fields", models.JSONField()),
                        ("ct", models.BigIntegerField()),
                        ("ut", models.BigIntegerField()),
                    ],
                    options={
                        "db_table": "content_meta",
                    },
                ),
                migrations.CreateModel(
                    name="CmsMediaFile",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("original_name", models.CharField(max_length=255)),
                        ("mime_type", models.PositiveSmallIntegerField(default=0)),
                        ("size_bytes", models.PositiveBigIntegerField(default=0)),
                        ("raw_path", models.CharField(max_length=255)),
                        (
                            "transcoded_path",
                            models.CharField(blank=True, max_length=255, null=True),
                        ),
                        ("cdn_url", models.CharField(blank=True, max_length=255, null=True)),
                        ("status", models.PositiveSmallIntegerField(default=0)),
                        ("error_message", models.TextField(blank=True, null=True)),
                        ("ct", models.BigIntegerField()),
                        ("ut", models.BigIntegerField()),
                    ],
                    options={
                        "db_table": "media_file",
                    },
                ),
            ],
        ),
    ]
