# Generated by Django 4.1.13 on 2026-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Batch",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("content", models.TextField(blank=True, default="")),
                        ("source_type", models.SmallIntegerField(db_index=True, default=0)),
                        ("ct", models.BigIntegerField(db_index=True, default=0)),
                        ("ut", models.BigIntegerField(db_index=True, default=0)),
                    ],
                    options={
                        "db_table": "batch",
                        "ordering": ["-ct"],
                    },
                ),
                migrations.CreateModel(
                    name="Insight",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("content", models.TextField(help_text="观点内容")),
                        (
                            "type",
                            models.SmallIntegerField(
                                choices=[(0, "矛盾发现"), (1, "路径推理"), (2, "跨文本综合")],
                                db_index=True,
                                default=1,
                            ),
                        ),
                        (
                            "status",
                            models.SmallIntegerField(
                                choices=[(0, "草稿"), (1, "已采纳")], db_index=True, default=0
                            ),
                        ),
                        (
                            "perspective",
                            models.SmallIntegerField(
                                blank=True,
                                choices=[(0, "人物"), (1, "概念"), (2, "指标")],
                                db_index=True,
                                default=1,
                                help_text="视角类型 0=人物 1=概念 2=指标",
                                null=True,
                            ),
                        ),
                        ("ct", models.BigIntegerField(db_index=True, default=0)),
                        ("ut", models.BigIntegerField(db_index=True, default=0)),
                    ],
                    options={
                        "db_table": "insight",
                        "ordering": ["-ut"],
                    },
                ),
                migrations.CreateModel(
                    name="KnowledgePoint",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        (
                            "batch_id",
                            models.BigIntegerField(
                                blank=True,
                                db_index=True,
                                help_text="同一批输入的分组 id",
                                null=True,
                            ),
                        ),
                        ("content", models.TextField()),
                        (
                            "seq",
                            models.IntegerField(
                                default=0, help_text="在 batch 内的顺序，0-based"
                            ),
                        ),
                        ("brief", models.TextField(blank=True, null=True)),
                        (
                            "graph_brief",
                            models.TextField(blank=True, db_column="g_brief", null=True),
                        ),
                        (
                            "graph_subject",
                            models.TextField(blank=True, db_column="g_sub", null=True),
                        ),
                        (
                            "graph_object",
                            models.TextField(blank=True, db_column="g_obj", null=True),
                        ),
                        (
                            "vec_sub_deco_id",
                            models.CharField(
                                blank=True,
                                db_column="v_sub_deco_id",
                                help_text="Mongo Atlas sub_deco collection document _id for vector update",
                                max_length=32,
                                null=True,
                            ),
                        ),
                        (
                            "vec_obj_deco_id",
                            models.CharField(
                                blank=True,
                                db_column="v_obj_deco_id",
                                help_text="Mongo Atlas obj_deco collection document _id for vector update",
                                max_length=32,
                                null=True,
                            ),
                        ),
                        (
                            "graph_brief_hash",
                            models.IntegerField(
                                blank=True, db_column="g_brief_hash", db_index=True, null=True
                            ),
                        ),
                        (
                            "graph_subject_hash",
                            models.IntegerField(
                                blank=True, db_column="g_sub_hash", db_index=True, null=True
                            ),
                        ),
                        (
                            "graph_object_hash",
                            models.IntegerField(
                                blank=True, db_column="g_obj_hash", db_index=True, null=True
                            ),
                        ),
                        ("classification", models.SmallIntegerField(db_index=True, default=1)),
                        ("stage", models.SmallIntegerField(db_index=True, default=0)),
                        ("status", models.SmallIntegerField(db_index=True, default=0)),
                        ("ct", models.BigIntegerField(db_index=True, default=0)),
                        ("ut", models.BigIntegerField(db_index=True, default=0)),
                    ],
                    options={
                        "db_table": "knowledge",
                        "ordering": ["batch_id", "seq"],
                    },
                ),
                migrations.AddIndex(
                    model_name="knowledgepoint",
                    index=models.Index(
                        fields=["batch_id"], name="knowledge_batch_i_5a26e7_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="knowledgepoint",
                    index=models.Index(fields=["stage"], name="knowledge_stage_49668e_idx"),
                ),
                migrations.AddIndex(
                    model_name="knowledgepoint",
                    index=models.Index(fields=["status"], name="knowledge_status_dffb8f_idx"),
                ),
            ],
        ),
    ]
