# Generated by Django 4.1.13 on 2026-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Event",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("biz_type", models.SmallIntegerField(db_index=True, default=0)),
                        ("status", models.SmallIntegerField(db_index=True, default=0)),
                        ("level", models.SmallIntegerField(db_index=True, default=3)),
                        (
                            "verify_code_id",
                            models.PositiveBigIntegerField(db_index=True, default=0),
                        ),
                        (
                            "verify_ref_id",
                            models.PositiveBigIntegerField(db_index=True, default=0),
                        ),
                        (
                            "notice_target",
                            models.CharField(blank=True, default="", max_length=255),
                        ),
                        ("notice_channel", models.SmallIntegerField(db_index=True, default=0)),
                        ("payload_json", models.TextField(default="{}")),
                        ("message", models.CharField(blank=True, default="", max_length=255)),
                        ("ct", models.PositiveBigIntegerField(db_index=True, default=0)),
                        ("ut", models.PositiveBigIntegerField(db_index=True, default=0)),
                    ],
                    options={
                        "db_table": "event",
                    },
                ),
                migrations.CreateModel(
                    name="Token",
                    fields=[
                        ("id", models.AutoField(primary_key=True, serialize=False)),
                        ("user_id", models.BigIntegerField(db_index=True)),
                        ("token", models.CharField(default="", max_length=512)),
                        ("refresh", models.CharField(default="", max_length=255)),
                        ("status", models.SmallIntegerField(db_index=True, default=0)),
                        ("expires_at", models.PositiveBigIntegerField(default=0)),
                        ("ct", models.PositiveBigIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "token",
                    },
                ),
                migrations.CreateModel(
                    name="User",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        (
                            "username",
                            models.CharField(
                                db_column="name", db_index=True, max_length=64, unique=True
                            ),
                        ),
                        (
                            "password_hash",
                            models.CharField(db_column="pw_hash", max_length=255),
                        ),
                        (
                            "email",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                default="",
                                max_length=255,
                                unique=True,
                            ),
                        ),
                        (
                            "phone",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                default="",
                                max_length=32,
                                unique=True,
                            ),
                        ),
                        ("avatar", models.CharField(blank=True, default="", max_length=512)),
                        (
                            "status",
                            models.SmallIntegerField(
                                choices=[(0, "DISABLED"), (1, "ENABLED")],
                                db_index=True,
                                default=0,
                            ),
                        ),
                        (
                            "auth_status",
                            models.PositiveSmallIntegerField(
                                db_column="auth_status", db_index=True, default=0
                            ),
                        ),
                        (
                            "ctrl_status",
                            models.SmallIntegerField(
                                choices=[(0, "NONE"), (1, "LOGIN_FORBIDDEN")],
                                db_index=True,
                                default=0,
                            ),
                        ),
                        (
                            "ctrl_reason",
                            models.CharField(blank=True, default="", max_length=512),
                        ),
                        ("ext", models.TextField(default="{}")),
                        ("ct", models.PositiveBigIntegerField(db_index=True, default=0)),
                        ("ut", models.PositiveBigIntegerField(db_index=True, default=0)),
                    ],
                    options={
                        "db_table": "user",
                    },
                ),
                migrations.AddIndex(
                    model_name="user",
                    index=models.Index(fields=["status"], name="user_status_116710_idx"),
                ),
                migrations.AddIndex(
                    model_name="user",
                    index=models.Index(fields=["ct"], name="user_ct_7f7eb9_idx"),
                ),
                migrations.AddIndex(
                    model_name="token",
                    index=models.Index(
                        fields=["user_id", "status"], name="token_user_id_6487e2_idx"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="token",
                    constraint=models.UniqueConstraint(
                        fields=("user_id", "token"), name="uni_user_token_token"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="token",
                    constraint=models.UniqueConstraint(
                        fields=("user_id", "refresh"), name="uni_user_token_refresh"
                    ),
                ),
                migrations.AddIndex(
                    model_name="event",
                    index=models.Index(
                        fields=["biz_type", "status", "ct"], name="event_biz_typ_d72020_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="event",
                    index=models.Index(
                        fields=["verify_code_id"], name="event_verify__082e0c_idx"
                    ),
                ),
            ],
        ),
    ]
