# Generated by Django 4.1.13 on 2026-04-11 04:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="SearchRecDocTerm",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("doc_key", models.CharField(max_length=191)),
                        ("term", models.CharField(max_length=191)),
                        ("tf", models.PositiveIntegerField(default=1)),
                    ],
                    options={
                        "db_table": "doc_term",
                    },
                ),
                migrations.CreateModel(
                    name="SearchRecDocument",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("doc_key", models.CharField(max_length=191)),
                        ("title", models.CharField(max_length=512)),
                        ("content", models.TextField()),
                        ("tags", models.TextField(default="")),
                        ("lexical_norm_sq", models.BigIntegerField(default=0)),
                        (
                            "score_boost",
                            models.DecimalField(
                                decimal_places=2, default=Decimal("1.00"), max_digits=4
                            ),
                        ),
                        (
                            "popularity_score",
                            models.DecimalField(
                                decimal_places=4, default=Decimal("0"), max_digits=5
                            ),
                        ),
                        (
                            "freshness_score",
                            models.DecimalField(
                                decimal_places=4, default=Decimal("0"), max_digits=5
                            ),
                        ),
                        ("ct", models.BigIntegerField()),
                        ("ut", models.BigIntegerField()),
                    ],
                    options={
                        "db_table": "doc",
                    },
                ),
                migrations.CreateModel(
                    name="SearchRecEvent",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("uid", models.BigIntegerField(blank=True, null=True)),
                        ("did", models.CharField(blank=True, max_length=128, null=True)),
                        (
                            "event_type",
                            models.IntegerField(
                                choices=[
                                    (0, "Unknown"),
                                    (1, "Search Query"),
                                    (2, "Impression"),
                                    (3, "Click"),
                                    (4, "Upsert"),
                                ]
                            ),
                        ),
                        ("payload", models.TextField(default="{}")),
                        ("ct", models.BigIntegerField()),
                    ],
                    options={
                        "db_table": "event",
                    },
                ),
                migrations.CreateModel(
                    name="SearchRecReg",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=128)),
                        ("access_key", models.CharField(max_length=64)),
                        ("status", models.SmallIntegerField(default=0)),
                        ("ct", models.PositiveBigIntegerField(default=0)),
                        ("ut", models.PositiveBigIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "reg",
                    },
                ),
                migrations.AddIndex(
                    model_name="searchrecreg",
                    index=models.Index(fields=["name"], name="searchrec_reg_name_idx"),
                ),
                migrations.AddIndex(
                    model_name="searchrecreg",
                    index=models.Index(fields=["status"], name="searchrec_reg_status_idx"),
                ),
                migrations.AddConstraint(
                    model_name="searchrecreg",
                    constraint=models.UniqueConstraint(
                        fields=("access_key",), name="searchrec_reg_access_key_uniq"
                    ),
                ),
                migrations.AddField(
                    model_name="searchrecevent",
                    name="rid",
                    field=models.ForeignKey(
                        db_column="rid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="app_searchrec.searchrecreg",
                    ),
                ),
                migrations.AddField(
                    model_name="searchrecdocument",
                    name="rid",
                    field=models.ForeignKey(
                        db_column="rid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="app_searchrec.searchrecreg",
                    ),
                ),
                migrations.AddField(
                    model_name="searchrecdocterm",
                    name="rid",
                    field=models.ForeignKey(
                        db_column="rid",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doc_terms",
                        to="app_searchrec.searchrecreg",
                    ),
                ),
                migrations.AddIndex(
                    model_name="searchrecevent",
                    index=models.Index(
                        fields=["rid", "event_type", "ct"], name="idx_event_rid_type_ct"
                    ),
                ),
                migrations.AddIndex(
                    model_name="searchrecdocument",
                    index=models.Index(fields=["rid"], name="idx_searchrec_doc_rid"),
                ),
                migrations.AddConstraint(
                    model_name="searchrecdocument",
                    constraint=models.UniqueConstraint(
                        fields=("rid", "doc_key"), name="uniq_searchrec_doc_rid_key"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="searchrecdocument",
                    constraint=models.CheckConstraint(
                        check=models.Q(
                            ("popularity_score__gte", 0), ("popularity_score__lte", 1)
                        ),
                        name="searchrec_doc_popularity_unit",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="searchrecdocument",
                    constraint=models.CheckConstraint(
                        check=models.Q(
                            ("freshness_score__gte", 0), ("freshness_score__lte", 1)
                        ),
                        name="searchrec_doc_freshness_unit",
                    ),
                ),
                migrations.AddIndex(
                    model_name="searchrecdocterm",
                    index=models.Index(fields=["rid", "term"], name="idx_doc_term_rid_term"),
                ),
                migrations.AddConstraint(
                    model_name="searchrecdocterm",
                    constraint=models.UniqueConstraint(
                        fields=("rid", "doc_key", "term"), name="uniq_searchrec_doc_term_rid"
                    ),
                ),
            ],
        ),
    ]
