# Generated by Django 4.1.13 on 2026-04-09 12:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_searchrec", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchrecdocument",
            name="score_boost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=4
            ),
        ),
    ]
