# bit allocation
DATACENTER_BITS = 2
MACHINE_BITS = 3
RECOUNT_BITS = 2
BUSINESS_BITS = 3
TIMESTAMP_BITS = 41
SEQUENCE_BITS = 12

# mask values
MASK_DATACENTER_ID = (1 << DATACENTER_BITS) - 1
MASK_MACHINE_ID = (1 << MACHINE_BITS) - 1
MASK_RECOUNT = (1 << RECOUNT_BITS) - 1
MASK_BUSINESS_ID = (1 << BUSINESS_BITS) - 1
MASK_SEQUENCE = (1 << SEQUENCE_BITS) - 1

# maximum values
MAX_RECOUNT = MASK_RECOUNT + 1

# bit shifts (from right to left)
SEQUENCE_SHIFT = 0
BUSINESS_SHIFT = SEQUENCE_BITS
RECOUNT_SHIFT = SEQUENCE_BITS + BUSINESS_BITS
MACHINE_SHIFT = SEQUENCE_BITS + BUSINESS_BITS + RECOUNT_BITS
DATACENTER_SHIFT = SEQUENCE_BITS + BUSINESS_BITS + RECOUNT_BITS + MACHINE_BITS
TIMESTAMP_SHIFT = SEQUENCE_BITS + BUSINESS_BITS + RECOUNT_BITS + MACHINE_BITS + DATACENTER_BITS

# clock backward threshold
CLOCK_BACKWARD_THRESHOLD = 5  # milliseconds