"""
Django settings for service_foundation project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import logging
import os
from pathlib import Path

from common.utils.env_util import load_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Load environment variables with layered support (.env, .env.test, .env.prod)
env = load_env(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l7qc5yniq$_0fe*%e_6zzxw=4k@1q=))v25=q%4w7rj@0-vv5("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Handle ALLOWED_HOSTS configuration
# Support '*' to allow all hosts (useful for Docker containers)
# Also handle comma-separated string format from .env files
allowed_hosts_raw = os.environ.get("ALLOWED_HOSTS") or env("ALLOWED_HOSTS", default="localhost,127.0.0.1")
if allowed_hosts_raw == "*":
    ALLOWED_HOSTS = ["*"]
else:
    # Parse comma-separated string into list
    if isinstance(allowed_hosts_raw, str):
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.split(",") if host.strip()]
    else:
        ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=['localhost', '127.0.0.1'])

# Log ALLOWED_HOSTS configuration at startup (for debugging)
# Use print() to ensure output is visible in Docker logs (stdout)
print(f"[Django Settings] ALLOWED_HOSTS configured as: {ALLOWED_HOSTS} (from env: {allowed_hosts_raw})", flush=True)

# Local Info
HOST = env("HOST", default="127.0.0.1")
PORT = env("PORT", default=80)
THREAD = env("THREAD", default=1)

# Timezone
GMT = env("GMT", default="+00:00")

# App enable switches (controlled via environment variables)
APP_CONSOLE_ENABLED = env.bool("APP_CONSOLE_ENABLED", default=True)
APP_KNOW_ENABLED = env.bool("APP_KNOW_ENABLED", default=True)
APP_MAILSERVER_ENABLED = env.bool("APP_MAILSERVER_ENABLED", default=True)
APP_OSS_ENABLED = env.bool("APP_OSS_ENABLED", default=True)
APP_SNOWFLAKE_ENABLED = env.bool("APP_SNOWFLAKE_ENABLED", default=True)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_crontab",
    "rest_framework",
    "corsheaders",
]

# Dynamically add enabled apps
if APP_CONSOLE_ENABLED:
    INSTALLED_APPS.append("app_console")
if APP_KNOW_ENABLED:
    INSTALLED_APPS.append("app_know")
if APP_MAILSERVER_ENABLED:
    INSTALLED_APPS.append("app_mailserver")
if APP_OSS_ENABLED:
    INSTALLED_APPS.append("app_oss")
if APP_SNOWFLAKE_ENABLED:
    INSTALLED_APPS.append("app_snowflake")

MIDDLEWARE = [
    "log_request_id.middleware.RequestIDMiddleware",
    "common.middleware.host_validation_middleware.HostValidationMiddleware",  # Must be before SecurityMiddleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

# CORS
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = "service_foundation.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app_console.context_processors.console_context",
            ],
        },
    },
]

WSGI_APPLICATION = "service_foundation.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# Database configuration is now loaded from environment variables (.env, .env.test, .env.prod)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_DEFAULT_NAME", default="sf"),
        "USER": env("DB_DEFAULT_USER", default="root"),
        "PASSWORD": env("DB_DEFAULT_PASS", default=""),
        "HOST": env("DB_DEFAULT_HOST", default="127.0.0.1"),
        "PORT": env("DB_DEFAULT_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_DEFAULT_TEST_NAME", default="sf_test"),
        },
    },
    "know_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_KNOW_NAME", default="sf_know"),
        "USER": env("DB_KNOW_USER", default="zhang"),
        "PASSWORD": env("DB_KNOW_PASS", default=""),
        "HOST": env("DB_KNOW_HOST", default="127.0.0.1"),
        "PORT": env("DB_KNOW_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_KNOW_TEST_NAME", default="sf_know_test"),
        },
    },
    "mailserver_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_MAILSERVER_NAME", default="sf_mailserver"),
        "USER": env("DB_MAILSERVER_USER", default="zhang"),
        "PASSWORD": env("DB_MAILSERVER_PASS", default=""),
        "HOST": env("DB_MAILSERVER_HOST", default="127.0.0.1"),
        "PORT": env("DB_MAILSERVER_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_MAILSERVER_TEST_NAME", default="sf_mailserver_test"),
        },
    },
    "oss_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_OSS_NAME", default="sf_oss"),
        "USER": env("DB_OSS_USER", default="zhang"),
        "PASSWORD": env("DB_OSS_PASS", default=""),
        "HOST": env("DB_OSS_HOST", default="127.0.0.1"),
        "PORT": env("DB_OSS_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_OSS_TEST_NAME", default="sf_oss_test"),
        },
    },
    "snowflake_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_SNOWFLAKE_NAME", default="sf_snowflake"),
        "USER": env("DB_SNOWFLAKE_USER", default="zhang"),
        "PASSWORD": env("DB_SNOWFLAKE_PASS", default=""),
        "HOST": env("DB_SNOWFLAKE_HOST", default="127.0.0.1"),
        "PORT": env("DB_SNOWFLAKE_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_SNOWFLAKE_TEST_NAME", default="sf_snowflake_test"),
        },
    }
}

# Dynamically configure database routers based on enabled apps
DATABASE_ROUTERS = []
if APP_SNOWFLAKE_ENABLED:
    DATABASE_ROUTERS.append("app_snowflake.db_routers.ReadWriteRouter")
if APP_OSS_ENABLED:
    DATABASE_ROUTERS.append("app_oss.db_routers.ReadWriteRouter")
if APP_KNOW_ENABLED:
    DATABASE_ROUTERS.append("app_know.db_routers.ReadWriteRouter")

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} [{request_id}] {module:15.15} [{process:d}|{thread:d}] {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "filters": {
        'request_id': {
            '()': 'log_request_id.filters.RequestIDFilter'
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        }
    },
    "handlers": {
        "logfile": {
            "level": env("LOG_LEVEL", default="INFO"),
            "filters": ["request_id"],
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": env("LOG_DIR", default="log") + '/' + env("LOG_FILE", default="app.log"),
            "when": "D",
            "interval": 1,
            "backupCount": 14,
            "formatter": "verbose",
            "encoding": "utf8",
        },
        "console": {
            "level": "DEBUG",
            "filters": ["request_id", "require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        }
    },
    "loggers": {
        "django.db.backends": {
            "level": env("LOG_LEVEL_DJANGO_DB", default="INFO"),
            "handlers": [env("LOG_HANDLER", default="console")],
        },
        "service_foundation": {
            "level": env("LOG_LEVEL_APP_SERV_FD", default="INFO"),
            "handlers": [env("LOG_HANDLER", default="console")],
        },
        "app_mailserver": {
            "level": env("LOG_LEVEL_APP_MAILSERVER", default="INFO"),
            "handlers": [env("LOG_HANDLER", default="console")],
        },
        "app_oss": {
            "level": env("LOG_LEVEL_APP_OSS", default="INFO"),
            "handlers": [env("LOG_HANDLER", default="console")],
        },
        "app_snowflake": {
            "level": env("LOG_LEVEL_APP_SNOWFLAKE", default="INFO"),
            "handlers": [env("LOG_HANDLER", default="console")],
        },
        "app_know": {
            "level": env("LOG_LEVEL_APP_KNOW", default="INFO"),
            "handlers": [env("LOG_HANDLER", default="console")],
        },
        "common": {
            "level": env("LOG_LEVEL_COMMON", default="INFO"),
            "handlers": [env("LOG_HANDLER", default="console")],
        },
    }
}

# traceid
LOG_REQUEST_ID_HEADER = "X_Request_Id"
REQUEST_ID_RESPONSE_HEADER = "X_Request_Id"

# MongoDB Atlas configuration (for app_know)
MONGO_ATLAS_USER = env("MONGO_ATLAS_USER", default="")
MONGO_ATLAS_PASS = env("MONGO_ATLAS_PASS", default="")
MONGO_ATLAS_HOST = env("MONGO_ATLAS_HOST", default="cluster.mongodb.net")
MONGO_ATLAS_CLUSTER = env("MONGO_ATLAS_CLUSTER", default="cluster0")
MONGO_ATLAS_DB = env("MONGO_ATLAS_DB", default="know")

# Neo4j configuration (for app_know)
NEO4J_URI = env("NEO4J_URI", default="bolt://localhost:7687")
NEO4J_USER = env("NEO4J_USER", default="neo4j")
NEO4J_PASS = env("NEO4J_PASS", default="")
NEO4J_DATABASE = env("NEO4J_DATABASE", default="neo4j")
