"""
Django settings for service_foundation project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import logging
import os
import sys
from pathlib import Path
from typing import Any

from common.services.http.pools import HttpClientPool
from common.utils.env_util import load_env
from common.utils.redis_url_util import redis_location_with_db

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Load environment variables with layered support (.env, .env.test, .env.prod)
env = load_env(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l7qc5yniq$_0fe*%e_6zzxw=4k@1q=))v25=q%4w7rj@0-vv5("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

# COOP is meaningful on trustworthy origins (HTTPS or localhost). On plain http://<ip>:…
# browsers ignore the header and log a warning. Do not set by default; use HTTPS and
# set SECURE_CROSS_ORIGIN_OPENER_POLICY=same-origin in env when you terminate TLS.
SECURE_CROSS_ORIGIN_OPENER_POLICY = env("SECURE_CROSS_ORIGIN_OPENER_POLICY", default=None)

# WhiteNoise serves collected files from STATIC_ROOT. With DEBUG=False you must run
# collectstatic (see docker-entrypoint.sh). Optional: WHITENOISE_USE_FINDERS=true to
# resolve files via staticfiles finders when STATIC_ROOT is not populated (slower).
WHITENOISE_USE_FINDERS = env.bool("WHITENOISE_USE_FINDERS", default=False)

# Handle ALLOWED_HOSTS configuration
# Support '*' to allow all hosts (useful for Docker containers)
# Also handle comma-separated string format from .env files
allowed_hosts_raw = os.environ.get("ALLOWED_HOSTS") or env("ALLOWED_HOSTS", default="localhost,127.0.0.1")
if allowed_hosts_raw == "*":
    ALLOWED_HOSTS = ["*"]
else:
    # Parse comma-separated string into list
    if isinstance(allowed_hosts_raw, str):
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.split(",") if host.strip()]
    else:
        ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=['localhost', '127.0.0.1'])

# Log ALLOWED_HOSTS configuration at startup (for debugging)
# Use print() to ensure output is visible in Docker logs (stdout)
print(f"[Django Settings] ALLOWED_HOSTS configured as: {ALLOWED_HOSTS} (from env: {allowed_hosts_raw})", flush=True)

# Local Info
HOST = env("HOST", default="127.0.0.1")
PORT = env("PORT", default=80)
THREAD = env("THREAD", default=1)

# Timezone
GMT = env("GMT", default="+00:00")

# App enable switches (controlled via environment variables).
# APP_AIBROKER_ENABLED gates HTTP/console integration only; app_aibroker stays in
# INSTALLED_APPS so imports (views → services → models) do not depend on argv/IDE.
APP_AIBROKER_ENABLED = env.bool("APP_AIBROKER_ENABLED", default=True)
APP_CDN_ENABLED = env.bool("APP_CDN_ENABLED", default=True)
APP_CMS_ENABLED = env.bool("APP_CMS_ENABLED", default=True)
APP_CONSOLE_ENABLED = env.bool("APP_CONSOLE_ENABLED", default=True)
APP_KNOW_ENABLED = env.bool("APP_KNOW_ENABLED", default=True)
APP_MAILSERVER_ENABLED = env.bool("APP_MAILSERVER_ENABLED", default=False)
APP_NOTICE_ENABLED = env.bool("APP_NOTICE_ENABLED", default=True)
APP_OSS_ENABLED = env.bool("APP_OSS_ENABLED", default=True)
APP_SEARCHREC_ENABLED = env.bool("APP_SEARCHREC_ENABLED", default=True)
APP_SNOWFLAKE_ENABLED = env.bool("APP_SNOWFLAKE_ENABLED", default=True)
APP_USER_ENABLED = env.bool("APP_USER_ENABLED", default=True)
APP_VERIFY_ENABLED = env.bool("APP_VERIFY_ENABLED", default=True)
APP_CONFIG_ENABLED = env.bool("APP_CONFIG_ENABLED", default=True)
APP_KEEPCON_ENABLED = env.bool("APP_KEEPCON_ENABLED", default=False)
APP_TCC_ENABLED = env.bool("APP_TCC_ENABLED", default=False)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "simple_history",
    "django_crontab",
    "rest_framework",
    "corsheaders",
]

# Dynamically add enabled apps
if APP_AIBROKER_ENABLED:
    INSTALLED_APPS.append("app_aibroker.apps.AibrokerConfig")
if APP_CDN_ENABLED:
    INSTALLED_APPS.append("app_cdn.apps.CdnConfig")
if APP_CMS_ENABLED:
    INSTALLED_APPS.append("app_cms.apps.CmsConfig")
if APP_CONSOLE_ENABLED:
    INSTALLED_APPS.append("app_console")
if APP_KNOW_ENABLED:
    INSTALLED_APPS.append("app_know.apps.KnowConfig")
if APP_MAILSERVER_ENABLED:
    INSTALLED_APPS.append("app_mailserver.apps.MailserverConfig")
if APP_NOTICE_ENABLED:
    INSTALLED_APPS.append("app_notice.apps.AppNoticeConfig")
if APP_OSS_ENABLED:
    INSTALLED_APPS.append("app_oss.apps.OssConfig")
if APP_SEARCHREC_ENABLED:
    INSTALLED_APPS.append("app_searchrec.apps.AppSearchRecConfig")
if APP_SNOWFLAKE_ENABLED:
    INSTALLED_APPS.append("app_snowflake.apps.SnowflakeConfig")
if APP_USER_ENABLED:
    INSTALLED_APPS.append("app_user.apps.AppUserConfig")
if APP_VERIFY_ENABLED:
    INSTALLED_APPS.append("app_verify.apps.AppVerifyConfig")
if APP_CONFIG_ENABLED:
    INSTALLED_APPS.append("app_config.apps.ConfigAppConfig")
if APP_KEEPCON_ENABLED:
    INSTALLED_APPS.insert(0, "daphne")
    INSTALLED_APPS.append("channels")
    INSTALLED_APPS.append("app_keepcon.apps.KeepconConfig")
if APP_TCC_ENABLED:
    INSTALLED_APPS.append("app_tcc.apps.AppTccConfig")

MIDDLEWARE = [
    "log_request_id.middleware.RequestIDMiddleware",
    "common.middleware.host_validation_middleware.HostValidationMiddleware",  # Must be before SecurityMiddleware
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "common.utils.http_util.UnifiedExceptionMiddleware",
]

if APP_CONSOLE_ENABLED:
    _msg_mw = "django.contrib.messages.middleware.MessageMiddleware"
    _insert_at = MIDDLEWARE.index(_msg_mw)
    MIDDLEWARE.insert(_insert_at, "app_console.middleware.ConsoleStaffRequiredMiddleware")

REST_FRAMEWORK: dict[str, Any] = {
    "EXCEPTION_HANDLER": "common.utils.http_util.drf_unified_exception_handler",
    # Match compact JSON from API_JSON_DUMPS_PARAMS (no decorative whitespace in separators).
    "COMPACT_JSON": True,
    "UNICODE_JSON": True,
}

# CORS
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = "service_foundation.urls"

_TEMPLATE_CONTEXT_PROCESSORS = [
    "django.template.context_processors.debug",
    "django.template.context_processors.request",
    "django.contrib.auth.context_processors.auth",
    "django.contrib.messages.context_processors.messages",
]
if APP_CONSOLE_ENABLED:
    _TEMPLATE_CONTEXT_PROCESSORS.append("app_console.context_processors.console_context")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": _TEMPLATE_CONTEXT_PROCESSORS,
        },
    },
]

WSGI_APPLICATION = "service_foundation.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# Database configuration is now loaded from environment variables (.env, .env.test, .env.prod)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_DEFAULT_NAME", default="sf"),
        "USER": env("DB_DEFAULT_USER", default="root"),
        "PASSWORD": env("DB_DEFAULT_PASS", default=""),
        "HOST": env("DB_DEFAULT_HOST", default="127.0.0.1"),
        "PORT": env("DB_DEFAULT_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_DEFAULT_TEST_NAME", default="sf_test"),
        },
    },
    "aibroker_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_AIBROKER_NAME", default="sf_aibroker"),
        "USER": env("DB_AIBROKER_USER", default="zhang"),
        "PASSWORD": env("DB_AIBROKER_PASS", default=""),
        "HOST": env("DB_AIBROKER_HOST", default="127.0.0.1"),
        "PORT": env("DB_AIBROKER_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_AIBROKER_TEST_NAME", default="sf_aibroker_test"),
        },
    },
    "cdn_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_CDN_NAME", default="sf_cdn"),
        "USER": env("DB_CDN_USER", default="zhang"),
        "PASSWORD": env("DB_CDN_PASS", default=""),
        "HOST": env("DB_CDN_HOST", default="127.0.0.1"),
        "PORT": env("DB_CDN_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_CDN_TEST_NAME", default="sf_cdn_test"),
        },
    },
    "cms_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_CMS_NAME", default="sf_cms"),
        "USER": env("DB_CMS_USER", default="zhang"),
        "PASSWORD": env("DB_CMS_PASS", default=""),
        "HOST": env("DB_CMS_HOST", default="127.0.0.1"),
        "PORT": env("DB_CMS_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_CMS_TEST_NAME", default="sf_cms_test"),
        },
    },
    "know_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_KNOW_NAME", default="sf_know"),
        "USER": env("DB_KNOW_USER", default="zhang"),
        "PASSWORD": env("DB_KNOW_PASS", default=""),
        "HOST": env("DB_KNOW_HOST", default="127.0.0.1"),
        "PORT": env("DB_KNOW_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_KNOW_TEST_NAME", default="sf_know_test"),
        },
    },
    "mailserver_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_MAILSERVER_NAME", default="sf_mailserver"),
        "USER": env("DB_MAILSERVER_USER", default="zhang"),
        "PASSWORD": env("DB_MAILSERVER_PASS", default=""),
        "HOST": env("DB_MAILSERVER_HOST", default="127.0.0.1"),
        "PORT": env("DB_MAILSERVER_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_MAILSERVER_TEST_NAME", default="sf_mailserver_test"),
        },
    },
    "notice_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_NOTICE_NAME", default="sf_notice"),
        "USER": env("DB_NOTICE_USER", default="zhang"),
        "PASSWORD": env("DB_NOTICE_PASS", default=""),
        "HOST": env("DB_NOTICE_HOST", default="127.0.0.1"),
        "PORT": env("DB_NOTICE_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_NOTICE_TEST_NAME", default="sf_notice_test"),
        },
    },
    "oss_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_OSS_NAME", default="sf_oss"),
        "USER": env("DB_OSS_USER", default="zhang"),
        "PASSWORD": env("DB_OSS_PASS", default=""),
        "HOST": env("DB_OSS_HOST", default="127.0.0.1"),
        "PORT": env("DB_OSS_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_OSS_TEST_NAME", default="sf_oss_test"),
        },
    },
    "searchrec_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_SEARCHREC_NAME", default="sf_searchrec"),
        "USER": env("DB_SEARCHREC_USER", default="zhang"),
        "PASSWORD": env("DB_SEARCHREC_PASS", default=""),
        "HOST": env("DB_SEARCHREC_HOST", default="127.0.0.1"),
        "PORT": env("DB_SEARCHREC_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_SEARCHREC_TEST_NAME", default="sf_searchrec_test"),
        },
    },
    "snowflake_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_SNOWFLAKE_NAME", default="sf_snowflake"),
        "USER": env("DB_SNOWFLAKE_USER", default="zhang"),
        "PASSWORD": env("DB_SNOWFLAKE_PASS", default=""),
        "HOST": env("DB_SNOWFLAKE_HOST", default="127.0.0.1"),
        "PORT": env("DB_SNOWFLAKE_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            # Tests use the default test DB for this alias (no separate sf_snowflake_test schema).
            "MIRROR": "default",
        },
    },
    "user_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_USER_NAME", default="sf_user"),
        "USER": env("DB_USER_USER", default="zhang"),
        "PASSWORD": env("DB_USER_PASS", default=""),
        "HOST": env("DB_USER_HOST", default="127.0.0.1"),
        "PORT": env("DB_USER_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_USER_TEST_NAME", default="sf_user_test"),
        },
    },
    "verify_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_VERIFY_NAME", default="sf_verify"),
        "USER": env("DB_VERIFY_USER", default="zhang"),
        "PASSWORD": env("DB_VERIFY_PASS", default=""),
        "HOST": env("DB_VERIFY_HOST", default="127.0.0.1"),
        "PORT": env("DB_VERIFY_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_VERIFY_TEST_NAME", default="sf_verify_test"),
        },
    },
    "config_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_CONFIG_NAME", default="sf_config"),
        "USER": env("DB_CONFIG_USER", default="zhang"),
        "PASSWORD": env("DB_CONFIG_PASS", default=""),
        "HOST": env("DB_CONFIG_HOST", default="127.0.0.1"),
        "PORT": env("DB_CONFIG_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_CONFIG_TEST_NAME", default="sf_config_test"),
        },
    },
    "keepcon_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_KEEPCON_NAME", default="sf_keepcon"),
        "USER": env("DB_KEEPCON_USER", default="zhang"),
        "PASSWORD": env("DB_KEEPCON_PASS", default=""),
        "HOST": env("DB_KEEPCON_HOST", default="127.0.0.1"),
        "PORT": env("DB_KEEPCON_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_KEEPCON_TEST_NAME", default="sf_keepcon_test"),
        },
    },
    "tcc_rw": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_TCC_NAME", default="sf_tcc"),
        "USER": env("DB_TCC_USER", default="zhang"),
        "PASSWORD": env("DB_TCC_PASS", default=""),
        "HOST": env("DB_TCC_HOST", default="127.0.0.1"),
        "PORT": env("DB_TCC_PORT", default=3306),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
        "TEST": {
            "NAME": env("DB_TCC_TEST_NAME", default="sf_tcc_test"),
        },
    },
}

# Dynamically configure database routers based on enabled apps
DATABASE_ROUTERS = []
if APP_AIBROKER_ENABLED:
    DATABASE_ROUTERS.append("app_aibroker.db_routers.ReadWriteRouter")
if APP_CDN_ENABLED:
    DATABASE_ROUTERS.append("app_cdn.db_routers.ReadWriteRouter")
if APP_CMS_ENABLED:
    DATABASE_ROUTERS.append("app_cms.db_routers.ReadWriteRouter")
if APP_KNOW_ENABLED:
    DATABASE_ROUTERS.append("app_know.db_routers.ReadWriteRouter")
if APP_NOTICE_ENABLED:
    DATABASE_ROUTERS.append("app_notice.db_routers.ReadWriteRouter")
if APP_OSS_ENABLED:
    DATABASE_ROUTERS.append("app_oss.db_routers.ReadWriteRouter")
if APP_SEARCHREC_ENABLED:
    DATABASE_ROUTERS.append("app_searchrec.db_routers.ReadWriteRouter")
if APP_SNOWFLAKE_ENABLED:
    DATABASE_ROUTERS.append("app_snowflake.db_routers.ReadWriteRouter")
if APP_USER_ENABLED:
    DATABASE_ROUTERS.append("app_user.db_routers.ReadWriteRouter")
if APP_VERIFY_ENABLED:
    DATABASE_ROUTERS.append("app_verify.db_routers.ReadWriteRouter")
if APP_CONFIG_ENABLED:
    DATABASE_ROUTERS.append("app_config.db_routers.ReadWriteRouter")
if APP_KEEPCON_ENABLED:
    DATABASE_ROUTERS.append("app_keepcon.db_routers.ReadWriteRouter")
if APP_TCC_ENABLED:
    DATABASE_ROUTERS.append("app_tcc.db_routers.ReadWriteRouter")


# Cache — base URL without /db; each app that uses Django cache sets its own DB + key segment.
CACHE_REDIS_URL = env("CACHE_REDIS_URL", default="redis://127.0.0.1:6379")
GLOBAL_CACHE_REDIS_KEY_PREFIX = env("GLOBAL_CACHE_REDIS_KEY_PREFIX", default="sf")
# User
USER_CACHE_REDIS_DB = env.int("USER_CACHE_REDIS_DB", default=1)
USER_CACHE_REDIS_KEY_PREFIX = env("USER_CACHE_REDIS_KEY_PREFIX", default="user")
CONFIG_CACHE_REDIS_DB = env.int("CONFIG_CACHE_REDIS_DB", default=1)
CONFIG_CACHE_REDIS_KEY_PREFIX = env("CONFIG_CACHE_REDIS_KEY_PREFIX", default="config")
CONFIG_CACHE_TTL_SECONDS = env.int("CONFIG_CACHE_TTL_SECONDS", default=300)

KEEPCON_CACHE_REDIS_DB = env.int("KEEPCON_CACHE_REDIS_DB", default=2)
KEEPCON_CACHE_REDIS_KEY_PREFIX = env("KEEPCON_CACHE_REDIS_KEY_PREFIX", default="keepcon")
# Redis keys for keepcon (Channels + ``CACHES['keepcon']``): ``{GLOBAL}:{KEEPCON_CACHE_REDIS_KEY_PREFIX}:…``
KEEPCON_REDIS_KEY_NAMESPACE = f"{GLOBAL_CACHE_REDIS_KEY_PREFIX}:{KEEPCON_CACHE_REDIS_KEY_PREFIX}"

if APP_KEEPCON_ENABLED:
    ASGI_APPLICATION = "service_foundation.asgi.application"
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    redis_location_with_db(CACHE_REDIS_URL, KEEPCON_CACHE_REDIS_DB),
                ],
                "prefix": KEEPCON_REDIS_KEY_NAMESPACE,
            },
        },
    }

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": redis_location_with_db(CACHE_REDIS_URL, USER_CACHE_REDIS_DB),
        "KEY_PREFIX": f"{GLOBAL_CACHE_REDIS_KEY_PREFIX}:{USER_CACHE_REDIS_KEY_PREFIX}",
    },
    "config": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": redis_location_with_db(CACHE_REDIS_URL, CONFIG_CACHE_REDIS_DB),
        "KEY_PREFIX": f"{GLOBAL_CACHE_REDIS_KEY_PREFIX}:{CONFIG_CACHE_REDIS_KEY_PREFIX}",
    },
}
if APP_KEEPCON_ENABLED:
    CACHES["keepcon"] = {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": redis_location_with_db(CACHE_REDIS_URL, KEEPCON_CACHE_REDIS_DB),
        "KEY_PREFIX": KEEPCON_REDIS_KEY_NAMESPACE,
    }

# Prime ``get_dict_by_codes`` LRU at startup (comma-separated); matches perf/locust smoke default.
DICT_HTTP_PRIME_CODES = env("DICT_HTTP_PRIME_CODES", default="aibroker_nested_param_type")


# app_cms
CMS_PROFILE = env("CMS_PROFILE", default="commerce")
CMS_LIST_PER_PAGE = env.int("CMS_LIST_PER_PAGE", default=15)
CMS_LIST_PER_PAGE_MAX = env.int("CMS_LIST_PER_PAGE_MAX", default=50)
CMS_EXPOSE_META = env.bool("CMS_EXPOSE_META", default=True)

# app_user: login brute-force counters (separate limits for login key vs client IP).
USER_LOGIN_FAIL_MAX_ATTEMPTS_LOGIN_KEY = env.int("USER_LOGIN_FAIL_MAX_ATTEMPTS_LOGIN_KEY", default=5)
USER_LOGIN_FAIL_MAX_ATTEMPTS_IP = env.int("USER_LOGIN_FAIL_MAX_ATTEMPTS_IP", default=20)
USER_LOGIN_FAIL_WINDOW_SECONDS = env.int("USER_LOGIN_FAIL_WINDOW_SECONDS", default=900)
# Password OK but disposition blocks login: throttle per (login_key, client_ip), separate from wrong-password counters.
USER_DISPOSITION_AUTH_THROTTLE_WINDOW_SECONDS = env.int(
    "USER_DISPOSITION_AUTH_THROTTLE_WINDOW_SECONDS",
    default=300,
)
USER_DISPOSITION_AUTH_THROTTLE_MAX = env.int("USER_DISPOSITION_AUTH_THROTTLE_MAX", default=30)


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Console uses django.contrib.auth sessions (staff users); separate from app_user API JWT.
LOGIN_URL = "/console/login/"
LOGIN_REDIRECT_URL = "/console/"
LOGOUT_REDIRECT_URL = "/console/login/"

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
# Note: STATIC_URL and STATIC_ROOT are set at top of file. Do not override here.
# STATIC_URL must be '/static/' (absolute) so styles work correctly when page is at /console/ etc.

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Request body size limit (bytes). Default 100MB for OSS uploads.
# Required for file-io and other services uploading to /api/oss
DATA_UPLOAD_MAX_MEMORY_SIZE = env.int("DATA_UPLOAD_MAX_MEMORY_SIZE", default=104857600)

# Build logging config with resilient logfile handler
_log_handler = env("LOG_HANDLER", default="console")
_log_file_path = env("LOG_FILE_PATH", default="log")
_log_path = Path(_log_file_path)
if not _log_path.is_absolute():
    _log_path = BASE_DIR / _log_path
# 日志路径（当 LOG_HANDLER=logfile 时写入该文件）：
# 默认 = <项目根目录>/log/app.log
# 可通过环境变量 LOG_FILE_PATH、LOG_FILE 覆盖
_log_path = _log_path / env("LOG_FILE", default="app.log")
_logfile_ok = False
if _log_handler == "logfile":
    try:
        _log_path.parent.mkdir(parents=True, exist_ok=True)
        # Test if we can open the file (same check TimedRotatingFileHandler will do)
        with open(_log_path, "a", encoding="utf-8"):
            pass
        _logfile_ok = True
    except (OSError, PermissionError) as e:
        import sys

        print(
            f"[Django Settings] logfile handler unavailable ({e}), falling back to console",
            file=sys.stderr,
        )
        _log_handler = "console"

# StreamHandler：不在生产环境使用 RequireDebugTrue，否则 DEBUG=False 时（常见 Docker 部署）
# 所有走 console handler 的 app_* / 自定义 logger 日志会被丢弃，docker logs 看不到排错信息。
_logging_handlers = {
    "console": {
        "level": "DEBUG",
        "filters": ["request_id"],
        "class": "logging.StreamHandler",
        "formatter": "simple",
    }
}
if _logfile_ok:
    _logging_handlers["logfile"] = {
        "level": env("LOG_LEVEL", default="INFO"),
        "filters": ["request_id"],
        "class": "logging.handlers.TimedRotatingFileHandler",
        "filename": str(_log_path),
        "when": "D",
        "interval": 1,
        "backupCount": 14,
        "formatter": "verbose",
        "encoding": "utf8",
    }

LOGGING = {
    "version": 1,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} [{request_id}] {module:15.15} [{process:d}|{thread:d}] {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "filters": {
        "request_id": {
            "()": "log_request_id.filters.RequestIDFilter",
        },
    },
    "handlers": _logging_handlers,
    "loggers": {
        "django.request": {
            "level": "ERROR",
            "handlers": [_log_handler],
            "propagate": False,
        },
        "django.db.backends": {
            "level": env("LOG_LEVEL_DJANGO_DB", default="INFO"),
            "handlers": [_log_handler],
        },
        "service_foundation": {
            "level": env("LOG_LEVEL_APP_SERV_FD", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_aibroker": {
            "level": env("LOG_LEVEL_APP_AIBROKER", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_cdn": {
            "level": env("LOG_LEVEL_APP_CDN", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_cms": {
            "level": env("LOG_LEVEL_APP_CMS", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_console": {
            "level": env("LOG_LEVEL_APP_CONSOLE", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_know": {
            "level": env("LOG_LEVEL_APP_KNOW", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_mailserver": {
            "level": env("LOG_LEVEL_APP_MAILSERVER", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_notice": {
            "level": env("LOG_LEVEL_APP_NOTICE", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_oss": {
            "level": env("LOG_LEVEL_APP_OSS", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_searchrec": {
            "level": env("LOG_LEVEL_APP_SEARCHREC", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_snowflake": {
            "level": env("LOG_LEVEL_APP_SNOWFLAKE", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_user": {
            "level": env("LOG_LEVEL_APP_USER", default="INFO"),
            "handlers": [_log_handler],
        },
        "app_verify": {
            "level": env("LOG_LEVEL_APP_VERIFY", default="INFO"),
            "handlers": [_log_handler],
        },
        "common": {
            "level": env("LOG_LEVEL_COMMON", default="INFO"),
            "handlers": [_log_handler],
        },
    }
}

# traceid
LOG_REQUEST_ID_HEADER = "X_Request_Id"
REQUEST_ID_RESPONSE_HEADER = "X_Request_Id"

# Internal HTTP integration
AIBROKER_SERVICE_URL = env("AIBROKER_SERVICE_URL", default="http://127.0.0.1:8000/api/ai")
# Console「调试」调用写入 call_log 时使用的 reg 主键；须在 aibroker 库中存在对应调用方
AIBROKER_REG_ID_TEST = env.int("AIBROKER_REG_ID_TEST", default=0)
AI_PROVIDER_ID_GET_VIDEO = env.int("AI_PROVIDER_ID_GET_VIDEO", default=0)
PROMPT_TEMPLATE_ID_ASK_AND_ANSWER = env.int("PROMPT_TEMPLATE_ID_ASK_AND_ANSWER", default=0)
PROMPT_TEMPLATE_ID_SUMMARY = env.int("PROMPT_TEMPLATE_ID_SUMMARY", default=0)
PROMPT_TEMPLATE_ID_RELATION_EXTRACT = env.int("PROMPT_TEMPLATE_ID_RELATION_EXTRACT", default=0)

NOTICE_SERVICE_URL = env("NOTICE_SERVICE_URL", default="http://127.0.0.1:8000/api/notice/send")
# 控制台「手动发送」默认写入 notice 记录的 event_id（可改为业务侧约定值）
NOTICE_CONSOLE_MANUAL_EVENT_ID = env.int("NOTICE_CONSOLE_MANUAL_EVENT_ID", default=1)
# Console SearchRec「API 调试」页示例 JSON 中的 access_key；未设置环境变量时为空字符串
CONSOLE_SEARCHREC_ACCESS_KEY = env("CONSOLE_SEARCHREC_ACCESS_KEY", default="")
CONSOLE_SNOWFLAKE_ACCESS_KEY = env("CONSOLE_SNOWFLAKE_ACCESS_KEY", default="")
# app_tcc: snowflake id allocation (POST JSON {access_key})；完整 URL，例如 https://api.example.com/api/snowflake/id
TCC_SNOWFLAKE_ACCESS_KEY = env("TCC_SNOWFLAKE_ACCESS_KEY", default="")
TCC_SNOWFLAKE_ID_URL = env("TCC_SNOWFLAKE_ID_URL", default="")
TCC_SNOWFLAKE_HTTP_TIMEOUT_SEC = env.float("TCC_SNOWFLAKE_HTTP_TIMEOUT_SEC", default=10.0)
TCC_OUTBOUND_TIMEOUT_SEC = env.float("TCC_OUTBOUND_TIMEOUT_SEC", default=30.0)
TCC_PHASE_TRY_TIMEOUT_SECONDS = env.int("TCC_PHASE_TRY_TIMEOUT_SECONDS", default=120)
TCC_PHASE_CONFIRM_TIMEOUT_SECONDS = env.int("TCC_PHASE_CONFIRM_TIMEOUT_SECONDS", default=120)
TCC_PHASE_CANCEL_TIMEOUT_SECONDS = env.int("TCC_PHASE_CANCEL_TIMEOUT_SECONDS", default=120)
TCC_AWAIT_CONFIRM_TIMEOUT_SECONDS = env.int("TCC_AWAIT_CONFIRM_TIMEOUT_SECONDS", default=300)
TCC_MAX_AUTO_RETRIES = env.int("TCC_MAX_AUTO_RETRIES", default=10)
TCC_DEFAULT_AUTO_CONFIRM = env.bool("TCC_DEFAULT_AUTO_CONFIRM", default=True)
# app_tcc scan: when phase_deadline_at is missing, next_retry cap (see scan_service.process_one)
TCC_SCAN_PHASE_DEADLINE_FALLBACK_MS = env.int("TCC_SCAN_PHASE_DEADLINE_FALLBACK_MS", default=60000)
TCC_SCAN_NEXT_RETRY_CAP_MS = env.int("TCC_SCAN_NEXT_RETRY_CAP_MS", default=15000)
# 运行监控页服务端拉取 AIBroker 汇总指标（仅服务端使用，勿下发到前端脚本）
CONSOLE_AIBROKER_ACCESS_KEY = env("CONSOLE_AIBROKER_ACCESS_KEY", default="")
CONSOLE_AIBROKER_METRICS_WINDOW_MS = env.int("CONSOLE_AIBROKER_METRICS_WINDOW_MS", default=86400000)
# 可选：携带 ?token= 或请求头 X-Console-Monitoring-Token 访问 /console/api/monitoring.json
CONSOLE_MONITORING_JSON_TOKEN = env("CONSOLE_MONITORING_JSON_TOKEN", default="")
# 运行监控页自动刷新间隔（毫秒）；0 表示不自动刷新
CONSOLE_MONITORING_REFRESH_MS = env.int("CONSOLE_MONITORING_REFRESH_MS", default=60000)
# Fire-and-forget notice delivery after enqueue (ThreadPoolExecutor cap per worker process)
NOTICE_SEND_THREAD_POOL_MAX_WORKERS = env.int("NOTICE_SEND_THREAD_POOL_MAX_WORKERS", default=8)

# wecom 酱 (Server酱 Turbo): SendKey in API path {base}/{SendKey}.send
NOTICE_BROKER_JIANG_URL = env("NOTICE_BROKER_JIANG_URL", default="https://sctapi.ftqq.com")
NOTICE_BROKER_JIANG_SEND_KEY = (env("NOTICE_BROKER_JIANG_SEND_KEY", default="") or "").strip()

VERIFY_REQUEST_URL = env("VERIFY_REQUEST_URL", default="http://127.0.0.1:8000/api/verify/request")
VERIFY_CHECK_URL = env("VERIFY_CHECK_URL", default="http://127.0.0.1:8000/api/verify/check")
VERIFY_CODE_TTL_SECONDS = env.int("VERIFY_CODE_TTL_SECONDS", default=300)

KNOW_AIBROKER_ACCESS_KEY = env("KNOW_AIBROKER_ACCESS_KEY", default="")
KNOW_SIMILARITY_REUSE_THRESHOLD = env.float("KNOW_SIMILARITY_REUSE_THRESHOLD", default=0.99)

USER_NOTICE_ACCESS_KEY = env("USER_NOTICE_ACCESS_KEY", default="")

USER_OSS_ENDPOINT = env("USER_OSS_ENDPOINT", default="http://127.0.0.1:8000/api/oss")
USER_OSS_BUCKET = env("USER_OSS_BUCKET", default="user-avatar")

# AI Broker multimodal: HTTP PUT to app_oss (S3-compatible), same host or peer URL as USER_OSS.
AIBROKER_OSS_ENDPOINT = env("AIBROKER_OSS_ENDPOINT", default="http://127.0.0.1:8000/api/oss")
AIBROKER_OSS_BUCKET = env("AIBROKER_OSS_BUCKET", default="aibroker-mm")
AIBROKER_OSS_MAX_BYTES_PER_FILE = env.int("AIBROKER_OSS_MAX_BYTES_PER_FILE", default=20 * 1024 * 1024)

USER_VERIFY_ACCESS_KEY = env("USER_VERIFY_ACCESS_KEY", default="")

# HTTP client pools (httpx)
HTTPX_DEFAULT_MAX_CONNECTIONS = env.int("HTTPX_DEFAULT_MAX_CONNECTIONS", default=100)
HTTPX_DEFAULT_MAX_KEEPALIVE = env.int("HTTPX_DEFAULT_MAX_KEEPALIVE", default=20)
HTTPX_DEFAULT_KEEPALIVE_EXPIRY = env.float("HTTPX_DEFAULT_KEEPALIVE_EXPIRY", default=30.0)
HTTPX_DEFAULT_TIMEOUT = env.float("HTTPX_DEFAULT_TIMEOUT", default=30.0)

HTTPX_WEBHOOK_MAX_CONNECTIONS = env.int("HTTPX_WEBHOOK_MAX_CONNECTIONS", default=64)
HTTPX_THIRD_PARTY_MAX_CONNECTIONS = env.int("HTTPX_THIRD_PARTY_MAX_CONNECTIONS", default=64)

HTTPX_POOL_MAX_CONNECTIONS = {
    HttpClientPool.WEBHOOK.value: HTTPX_WEBHOOK_MAX_CONNECTIONS,
    HttpClientPool.THIRD_PARTY.value: HTTPX_THIRD_PARTY_MAX_CONNECTIONS,
}

HTTPX_POOL_CELERY_QUEUE = {
    HttpClientPool.WEBHOOK.value: "webhook",
    HttpClientPool.THIRD_PARTY.value: "3rd_party",
}

# Search recommendation baseline config (remote adapters off by default = in-memory PoC)
SEARCHREC_OPENSEARCH_ENABLED = env.bool("SEARCHREC_OPENSEARCH_ENABLED", default=False)
SEARCHREC_MILVUS_ENABLED = env.bool("SEARCHREC_MILVUS_ENABLED", default=False)
SEARCHREC_QDRANT_ENABLED = env.bool("SEARCHREC_QDRANT_ENABLED", default=False)
SEARCHREC_FEAST_ENABLED = env.bool("SEARCHREC_FEAST_ENABLED", default=False)
SEARCHREC_MERGE_VECTOR_CANDIDATES = env.bool("SEARCHREC_MERGE_VECTOR_CANDIDATES", default=True)
SEARCHREC_SEARCH_CANDIDATE_MULTIPLIER = env.int("SEARCHREC_SEARCH_CANDIDATE_MULTIPLIER", default=2)
SEARCHREC_DEFAULT_TOP_K = env.int("SEARCHREC_DEFAULT_TOP_K", default=10)
SEARCHREC_HTTP_TIMEOUT = env.float("SEARCHREC_HTTP_TIMEOUT", default=3.0)
SEARCHREC_OPENSEARCH_URL = env("SEARCHREC_OPENSEARCH_URL", default="")
SEARCHREC_OPENSEARCH_INDEX = env("SEARCHREC_OPENSEARCH_INDEX", default="searchrec_docs")
SEARCHREC_OPENSEARCH_API_KEY = env("SEARCHREC_OPENSEARCH_API_KEY", default="")
SEARCHREC_MILVUS_ENDPOINT = env("SEARCHREC_MILVUS_ENDPOINT", default="")
SEARCHREC_MILVUS_COLLECTION = env("SEARCHREC_MILVUS_COLLECTION", default="searchrec_vectors")
SEARCHREC_MILVUS_API_KEY = env("SEARCHREC_MILVUS_API_KEY", default="")
SEARCHREC_QDRANT_URL = env("SEARCHREC_QDRANT_URL", default="")
SEARCHREC_QDRANT_COLLECTION = env("SEARCHREC_QDRANT_COLLECTION", default="searchrec_vectors")
SEARCHREC_QDRANT_API_KEY = env("SEARCHREC_QDRANT_API_KEY", default="")
SEARCHREC_FEAST_ONLINE_URL = env("SEARCHREC_FEAST_ONLINE_URL", default="")
SEARCHREC_FEAST_API_KEY = env("SEARCHREC_FEAST_API_KEY", default="")

# Celery + Redis
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "global_keyprefix": GLOBAL_CACHE_REDIS_KEY_PREFIX,
}
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_DEFAULT_QUEUE = env("CELERY_TASK_DEFAULT_QUEUE", default="default")
CELERY_TASK_ROUTES = {
    "common.services.task.distributed_tasks.sync_call_task": {"queue": "thirdparty"},
}

# MongoDB Atlas configuration
MONGO_ATLAS_USER = env("MONGO_ATLAS_USER", default="")
MONGO_ATLAS_PASS = env("MONGO_ATLAS_PASS", default="")
MONGO_ATLAS_HOST = env("MONGO_ATLAS_HOST", default="cluster.mongodb.net")
MONGO_ATLAS_CLUSTER = env("MONGO_ATLAS_CLUSTER", default="cluster0")
MONGO_ATLAS_DB = env("MONGO_ATLAS_DB", default="know")

# Neo4j configuration
NEO4J_URI = env("NEO4J_URI", default="bolt://localhost:7687")
NEO4J_USER = env("NEO4J_USER", default="neo4j")
NEO4J_PASS = env("NEO4J_PASS", default="")
NEO4J_DATABASE = env("NEO4J_DATABASE", default="neo4j")

# Warm bundled dict catalog at import (reduces first-request latency on /api/*/dict).
from common.dict_catalog.registry import warm_dict_catalog_bundled

warm_dict_catalog_bundled()
