# Generated by Django 4.1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Lexicon",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("name", models.CharField(max_length=128, unique=True)),
                        ("biz_type", models.PositiveSmallIntegerField(db_index=True, default=0)),
                        ("ct", models.PositiveBigIntegerField(default=0)),
                        ("ut", models.PositiveBigIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "lex",
                    },
                ),
                migrations.CreateModel(
                    name="LexiconVersion",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("lex_id", models.PositiveBigIntegerField(db_index=True)),
                        ("seq", models.PositiveIntegerField(default=1)),
                        ("status", models.SmallIntegerField(db_index=True, default=0)),
                        ("blob_relpath", models.CharField(default="", max_length=512)),
                        ("blob_checksum", models.CharField(default="", max_length=64)),
                        ("entry_count", models.PositiveIntegerField(default=0)),
                        ("published_at", models.PositiveBigIntegerField(default=0)),
                        ("ct", models.PositiveBigIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "lex_ver",
                    },
                ),
                migrations.CreateModel(
                    name="LexiconEntry",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("lex_id", models.PositiveBigIntegerField(db_index=True)),
                        ("word", models.CharField(db_index=True, max_length=512)),
                        ("label_id", models.PositiveBigIntegerField(db_index=True, default=0)),
                        ("suggestion", models.SmallIntegerField(db_index=True, default=0)),
                        ("priority", models.IntegerField(default=0)),
                        ("enabled", models.SmallIntegerField(db_index=True, default=1)),
                        ("ct", models.PositiveBigIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "lex_entry",
                    },
                ),
                migrations.AddIndex(
                    model_name="lexiconversion",
                    index=models.Index(fields=["lex_id", "status"], name="tm_lv_lex_status_idx"),
                ),
                migrations.AddIndex(
                    model_name="lexiconversion",
                    index=models.Index(fields=["lex_id", "seq"], name="tm_lv_lex_seq_idx"),
                ),
                migrations.AddIndex(
                    model_name="lexiconentry",
                    index=models.Index(fields=["lex_id", "enabled"], name="tm_le_lex_en_idx"),
                ),
            ],
        ),
    ]
