CREATE TABLE `d` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`arn` VARCHAR(256) NOT NULL DEFAULT '',
	`status` TINYINT(4) NOT NULL DEFAULT '0',
	`domain_name` VARCHAR(256) NOT NULL DEFAULT '',
	`origin_config` LONGTEXT NOT NULL,
	`aliases` LONGTEXT NOT NULL,
	`enabled` TINYINT(1) NOT NULL DEFAULT '0',
	`comment` VARCHAR(256) NOT NULL DEFAULT '',
	`etag` VARCHAR(64) NOT NULL DEFAULT '',
	`ct` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`ut` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
) COMMENT='CDN distribution' COLLATE='utf8mb4_unicode_ci';


CREATE TABLE `invalid` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`did` BIGINT(20) NOT NULL DEFAULT '0',
	`caller_reference` VARCHAR(128) NOT NULL DEFAULT '',
	`paths` TEXT NOT NULL,
	`status` SMALLINT(6) NOT NULL DEFAULT '0',
	`ct` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) USING BTREE
) COMMENT='CDN cache invalidation' COLLATE='utf8mb4_unicode_ci';
