# Generated by Django 4.1.13 on 2026-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Reg",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("name", models.CharField(max_length=128)),
                        ("access_key", models.CharField(max_length=64)),
                        (
                            "status",
                            models.SmallIntegerField(
                                choices=[(0, "DISABLED"), (1, "ENABLED")], default=0
                            ),
                        ),
                        ("ct", models.PositiveBigIntegerField(default=0)),
                        ("ut", models.PositiveBigIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "reg",
                    },
                ),
                migrations.CreateModel(
                    name="VerifyCode",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        (
                            "level",
                            models.SmallIntegerField(
                                choices=[(0, "PASS"), (1, "LOW"), (2, "MEDIUM"), (3, "HIGH")],
                                db_index=True,
                                default=0,
                            ),
                        ),
                        ("code", models.CharField(max_length=16)),
                        ("reg_id", models.PositiveBigIntegerField(db_index=True)),
                        ("ref_id", models.BigIntegerField(db_index=True)),
                        ("expires_at", models.PositiveBigIntegerField(db_index=True)),
                        ("used_at", models.PositiveBigIntegerField(db_index=True, default=0)),
                        ("ct", models.PositiveBigIntegerField(db_index=True, default=0)),
                    ],
                    options={
                        "db_table": "verify_code",
                    },
                ),
                migrations.CreateModel(
                    name="VerifyLog",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("reg_id", models.PositiveBigIntegerField(db_index=True, default=0)),
                        ("ref_id", models.BigIntegerField(db_index=True, default=0)),
                        (
                            "code_id",
                            models.PositiveBigIntegerField(
                                blank=True, db_index=True, null=True
                            ),
                        ),
                        ("level", models.SmallIntegerField(db_index=True, default=0)),
                        (
                            "action",
                            models.SmallIntegerField(
                                choices=[(1, "CODE_REQUEST"), (2, "CODE_CHECK")], db_index=True
                            ),
                        ),
                        ("ok", models.SmallIntegerField(db_index=True, default=1)),
                        ("message", models.CharField(default="", max_length=512)),
                        ("ct", models.PositiveBigIntegerField(db_index=True, default=0)),
                    ],
                    options={
                        "db_table": "verify_log",
                    },
                ),
                migrations.AddIndex(
                    model_name="verifylog",
                    index=models.Index(
                        fields=["reg_id", "ct"], name="verify_log_reg_id_01d5b1_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="verifylog",
                    index=models.Index(
                        fields=["code_id", "ct"], name="verify_log_code_id_6560e5_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="verifycode",
                    index=models.Index(
                        fields=["reg_id", "level", "ct"], name="verify_code_reg_id_51793d_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="verifycode",
                    index=models.Index(
                        fields=["ref_id", "level"], name="verify_code_ref_id_6eaa91_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="reg",
                    index=models.Index(fields=["name"], name="verify_reg_name_idx"),
                ),
                migrations.AddIndex(
                    model_name="reg",
                    index=models.Index(fields=["status"], name="verify_reg_status_idx"),
                ),
                migrations.AddIndex(
                    model_name="reg",
                    index=models.Index(fields=["ct"], name="verify_reg_ct_idx"),
                ),
                migrations.AddIndex(
                    model_name="reg",
                    index=models.Index(fields=["ut"], name="verify_reg_ut_idx"),
                ),
                migrations.AddConstraint(
                    model_name="reg",
                    constraint=models.UniqueConstraint(
                        fields=("access_key",), name="verify_reg_access_key_uniq"
                    ),
                ),
            ],
        ),
    ]
