# Generated by Django 4.1.13 on 2026-04-11 04:33

import app_cdn.enums.distribution_status_enum
import app_cdn.enums.invalidation_status_enum
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Distribution",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("arn", models.CharField(blank=True, default="", max_length=256)),
                        (
                            "status",
                            models.SmallIntegerField(
                                db_index=True,
                                default=app_cdn.enums.distribution_status_enum.DistributionStatusEnum[
                                    "DEPLOYED"
                                ],
                            ),
                        ),
                        ("domain_name", models.CharField(max_length=256)),
                        ("origin_config", models.TextField(default="{}")),
                        ("aliases", models.TextField(default="[]")),
                        ("enabled", models.BooleanField(default=False)),
                        ("comment", models.CharField(blank=True, default="", max_length=256)),
                        ("etag", models.CharField(blank=True, default="", max_length=64)),
                        ("ct", models.BigIntegerField(default=0)),
                        ("ut", models.BigIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "d",
                    },
                ),
                migrations.CreateModel(
                    name="Invalidation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("caller_reference", models.CharField(max_length=128)),
                        ("paths", models.TextField(default="[]")),
                        (
                            "status",
                            models.SmallIntegerField(
                                db_index=True,
                                default=app_cdn.enums.invalidation_status_enum.InvalidationStatusEnum[
                                    "COMPLETED"
                                ],
                            ),
                        ),
                        ("ct", models.BigIntegerField(default=0)),
                        (
                            "did",
                            models.ForeignKey(
                                db_column="did",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="invalidations",
                                to="app_cdn.distribution",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "invalid",
                    },
                ),
            ],
        ),
    ]
