# Generated by Django 4.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distribution_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("arn", models.CharField(blank=True, default="", max_length=256)),
                ("status", models.CharField(default="Deployed", max_length=32)),
                ("domain_name", models.CharField(max_length=256)),
                ("origin_config", models.TextField(default="{}")),
                ("aliases", models.TextField(default="[]")),
                ("enabled", models.BooleanField(default=True)),
                ("comment", models.CharField(blank=True, default="", max_length=256)),
                ("etag", models.CharField(blank=True, default="", max_length=64)),
                ("ct", models.BigIntegerField(default=0)),
                ("ut", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "cdn_distribution",
                "app_label": "app_cdn",
            },
        ),
        migrations.CreateModel(
            name="Invalidation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invalidation_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("caller_reference", models.CharField(max_length=128)),
                ("paths", models.TextField(default="[]")),
                ("status", models.CharField(default="Completed", max_length=32)),
                ("create_time", models.BigIntegerField(default=0)),
                ("distribution", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invalidations", to="app_cdn.distribution", db_index=True)),
            ],
            options={
                "db_table": "cdn_invalidation",
                "app_label": "app_cdn",
            },
        ),
    ]
